/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ulp.vista;

import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import ulp.entidades.Alumno;
import ulp.entidades.Materia;
import ulp.modelo.*;

/**
 *
 * @author Ezequiel
 */
public class ManejoInscripciones extends javax.swing.JInternalFrame {
    
    private AlumnoData ad;
    private MateriaData md;
    private InscripcionesData id;
    private Conexion conexion;
    
    private DefaultTableModel modelo_tabla;
    /**
     * Creates new form manejo_inscripciones
     */
    public ManejoInscripciones() {
        initComponents();
        try {
            conexion = new Conexion();
            ad = new AlumnoData(conexion);
            md = new MateriaData(conexion);
            id = new InscripcionesData(conexion);
            this.cargarAlumnos();
            modelo_tabla = new DefaultTableModel();
            this.armaCabeceraTabla();
            
        } catch (Exception e) {
            jl_form_ins_barra_estado.setText(e.getMessage());
        }
        
    }

    private void cargarAlumnos() {

        ad.ver_alumnos().forEach((alumno) -> {
            jcb_form_ins_lista_alumnos.addItem(alumno);
        });

    }
    
    private void armaCabeceraTabla() {
        //Titulos de Columnas
        ArrayList<Object> columnas = new ArrayList<>();
        columnas.add("ID");
        columnas.add("Nombre");
        columnas.forEach((it) -> {
            modelo_tabla.addColumn(it);
        });
        jt_form_ins_tabla_materias.setModel(modelo_tabla);
    }
    
    private void borraFilasTabla() {
        int a = modelo_tabla.getRowCount() - 1;
        for (int i = a; i >= 0; i--) {
            modelo_tabla.removeRow(i);
        }
    }
    
    public void cargaDatosInscriptas() {
        borraFilasTabla();
        //Llenar filas
        Alumno seleccionado = (Alumno) jcb_form_ins_lista_alumnos.getSelectedItem();
        List<Materia> lista = id.materias_alumno(seleccionado.getId_alumno());
        lista.forEach((m) -> {
            modelo_tabla.addRow(new Object[]{m.getId_materia(), m.getNombre_materia()});
        });
    }
    
    public void actualizarBarraEstado(String mensaje) {
        jl_form_ins_barra_estado.setText(mensaje);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbg_mostrar_cursadas_no_cursadas = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcb_form_ins_lista_alumnos = new javax.swing.JComboBox<>();
        jrd_form_ins_materias_inscripto = new javax.swing.JRadioButton();
        jrb_form_ins_materias_no_inscripto = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_form_ins_tabla_materias = new javax.swing.JTable();
        jl_form_ins_barra_estado = new javax.swing.JLabel();
        jb_form_ins_desinscribir = new javax.swing.JButton();
        jb_form_ins_inscribir = new javax.swing.JButton();
        jb_form_ins_salir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("FORMULARIO DE INSCRIPCIONES");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("ALUMNO");

        jbg_mostrar_cursadas_no_cursadas.add(jrd_form_ins_materias_inscripto);
        jrd_form_ins_materias_inscripto.setText("MATERIAS INSCRIPTO");
        jrd_form_ins_materias_inscripto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrd_form_ins_materias_inscriptoActionPerformed(evt);
            }
        });

        jbg_mostrar_cursadas_no_cursadas.add(jrb_form_ins_materias_no_inscripto);
        jrb_form_ins_materias_no_inscripto.setText("MATERIAS NO INSCRIPTO");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("LISTADO DE MATERIAS");

        jt_form_ins_tabla_materias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jt_form_ins_tabla_materias.setColumnSelectionAllowed(true);
        jt_form_ins_tabla_materias.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jt_form_ins_tabla_materias);
        jt_form_ins_tabla_materias.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jb_form_ins_desinscribir.setText("Anular inscripción");
        jb_form_ins_desinscribir.setEnabled(false);

        jb_form_ins_inscribir.setText("Inscribir");
        jb_form_ins_inscribir.setEnabled(false);

        jb_form_ins_salir.setText("Salir");
        jb_form_ins_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_form_ins_salirActionPerformed(evt);
            }
        });

        jLabel4.setText("Estado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(182, 182, 182)
                        .addComponent(jrd_form_ins_materias_inscripto)
                        .addGap(18, 18, 18)
                        .addComponent(jrb_form_ins_materias_no_inscripto))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jcb_form_ins_lista_alumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(134, 134, 134))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jb_form_ins_inscribir)
                        .addGap(116, 116, 116)
                        .addComponent(jb_form_ins_desinscribir)
                        .addGap(133, 133, 133)
                        .addComponent(jb_form_ins_salir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_form_ins_barra_estado, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcb_form_ins_lista_alumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jrd_form_ins_materias_inscripto)
                    .addComponent(jrb_form_ins_materias_no_inscripto))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_form_ins_desinscribir)
                    .addComponent(jb_form_ins_inscribir)
                    .addComponent(jb_form_ins_salir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_form_ins_barra_estado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrd_form_ins_materias_inscriptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrd_form_ins_materias_inscriptoActionPerformed
        // TODO add your handling code here:
        jb_form_ins_desinscribir.setEnabled(true);
        jb_form_ins_inscribir.setEnabled(false);
        this.cargaDatosInscriptas();
    }//GEN-LAST:event_jrd_form_ins_materias_inscriptoActionPerformed

    private void jb_form_ins_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_form_ins_salirActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jb_form_ins_salirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jb_form_ins_desinscribir;
    private javax.swing.JButton jb_form_ins_inscribir;
    private javax.swing.JButton jb_form_ins_salir;
    private javax.swing.ButtonGroup jbg_mostrar_cursadas_no_cursadas;
    private javax.swing.JComboBox<Alumno> jcb_form_ins_lista_alumnos;
    private javax.swing.JLabel jl_form_ins_barra_estado;
    private javax.swing.JRadioButton jrb_form_ins_materias_no_inscripto;
    private javax.swing.JRadioButton jrd_form_ins_materias_inscripto;
    private javax.swing.JTable jt_form_ins_tabla_materias;
    // End of variables declaration//GEN-END:variables
}
