/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ulp.vista;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import ulp.entidades.Alumno;
import ulp.entidades.Materia;
import ulp.modelo.AlumnoData;
import ulp.modelo.Conexion;
import ulp.modelo.InscripcionesData;
import ulp.modelo.MateriaData;

/**
 *
 * @author MArio
 */
public class MateriaAlta extends javax.swing.JInternalFrame {
        Conexion conexion = new Conexion();
        Alumno alumno;
        Materia materia;
        AlumnoData alumno_data;
        MateriaData materia_data;
        InscripcionesData ins_data;
        DefaultTableModel modelo;
        List<Materia> materias;
    /**
     * Creates new form MateriaAlta
     */
    public void Limpiar(){
        jtf_id.setText("");
        jtf_nombre.setText("");

    
    }
    public MateriaAlta() {
        initComponents();
        try {
        //Array instancias
        conexion = new Conexion();
        modelo=new DefaultTableModel();
        alumno_data = new AlumnoData(conexion);
        materia_data = new MateriaData(conexion);
        ins_data = new InscripcionesData(conexion);
        //Instancias Arrays
        materias=new ArrayList<>();
        this.armarCabeceraTabla();
        this.cargarMaterias();
        jb_guardar.setEnabled(false);
        } catch (Exception e) {
        }
    }
    public void cargarMaterias(){
        materias=materia_data.obtener_materias();
        for (Materia m:materias) {
        modelo.addRow(new Object[]{m.getId_materia(),m.getNombre_materia()});
        }
    
    }
            
            
    private void armarCabeceraTabla(){
       ArrayList<Object> columnas=new ArrayList<Object>();   
       columnas.add("ID");
       columnas.add("Nombre");
       for(Object it:columnas){
           modelo.addColumn(it);
       }
       jt_materia.setModel(modelo);
}
    
    public void borrarFilasTabla(){
       int a=jt_materia.getRowCount()-1;
       for(int i=a;i>=0;i--){
           modelo.removeRow(i);
       }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jb_guardar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtf_id = new javax.swing.JTextField();
        jtf_nombre = new javax.swing.JTextField();
        cajaSalida = new javax.swing.JLabel();
        jb_salir = new javax.swing.JButton();
        cajaSalida1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_materia = new javax.swing.JTable();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(6, 0), new java.awt.Dimension(6, 0), new java.awt.Dimension(6, 32767));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setText("Alta Materias");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 16, -1, -1));

        jb_guardar.setText("Guardar");
        jb_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_guardarActionPerformed(evt);
            }
        });
        getContentPane().add(jb_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 75, 147, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("ID Materia");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 77, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Nombre Materia");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 123, -1, -1));

        jtf_id.setEnabled(false);
        getContentPane().add(jtf_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 75, 74, -1));

        jtf_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_nombreActionPerformed(evt);
            }
        });
        jtf_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_nombreKeyTyped(evt);
            }
        });
        getContentPane().add(jtf_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 121, 185, -1));

        cajaSalida.setBackground(new java.awt.Color(0, 0, 255));
        cajaSalida.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        cajaSalida.setEnabled(false);
        getContentPane().add(cajaSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 173, 271, 23));

        jb_salir.setText("Salir");
        jb_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_salirActionPerformed(evt);
            }
        });
        getContentPane().add(jb_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 440, -1, -1));

        cajaSalida1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cajaSalida1.setForeground(new java.awt.Color(0, 0, 255));
        cajaSalida1.setEnabled(false);
        getContentPane().add(cajaSalida1, new org.netbeans.lib.awtextra.AbsoluteConstraints(521, 202, 299, 34));

        jLabel4.setText("Estado:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 151, -1, -1));

        jt_materia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Nombre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jt_materia);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 202, -1, 209));
        getContentPane().add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 450, 30, 40));
        getContentPane().add(filler2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 460, 40, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_guardarActionPerformed
        materia=new Materia();
        int cont=0;
        if("".equals(jtf_nombre.getText())){
            cont++;
            jtf_nombre.requestFocus();
        }
        if(cont==0){
        jb_guardar.setEnabled(true);
        materia.setNombre_materia(jtf_nombre.getText());
        materia_data.cargar_materia(materia);
        jtf_id.setText(Integer.toString(materia.getId_materia()));
        //cajaSalida.setText("Alumno guardado con Exito");
        this.borrarFilasTabla();
        this.cargarMaterias();
        this.Limpiar();
        }
        else{
            JOptionPane.showMessageDialog(this,"Debe ingresar el nombre de la Materia");
        }
    }//GEN-LAST:event_jb_guardarActionPerformed

    private void jb_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_salirActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jb_salirActionPerformed

    private void jtf_nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_nombreKeyTyped
        char c = evt.getKeyChar();
        if (Character.isDigit(c) == false || !(c > '5') ) {
            if(!"".equals(jtf_nombre.getText()))
            jb_guardar.setEnabled(true);
        } else {
            jb_guardar.setEnabled(false);
            evt.consume();
        }
//        char caracter = evt.getKeyChar();
// Verificar si la tecla pulsada no es un digito
//        if (((caracter < '0')
//                || (caracter > '9'))
//                && (caracter != '\b' /*corresponde a BACK_SPACE*/)) {
//            evt.consume();  // ignorar el evento de teclado
//        }

    }//GEN-LAST:event_jtf_nombreKeyTyped

    private void jtf_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_nombreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cajaSalida;
    private javax.swing.JLabel cajaSalida1;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jb_guardar;
    private javax.swing.JButton jb_salir;
    private javax.swing.JTable jt_materia;
    private javax.swing.JTextField jtf_id;
    private javax.swing.JTextField jtf_nombre;
    // End of variables declaration//GEN-END:variables
}
