/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ulp.vista;

import java.awt.Dimension;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JTextArea;

/**
 *
 * @author Genaro
 */
public class Principal extends javax.swing.JFrame {
//    public static String estados;
//    private VistasMateria visM = new VistasMateria;

    
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
//        System.out.println("a");
        
//        jLabel_estadosSistema.setText(traerEstados()+ "c");
//        jLabel_estadosSistema.setText(traerEstados()+ "d");
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu5 = new javax.swing.JMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanelEscritorio = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemArchivos_Salir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemMaterias_FormularioMateria = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemAlumnos_FormularioAlumno = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        javax.swing.JMenuItem jMenuItem_Inscripciones_FormularioInscripciones = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem_CargaDeNotas_Formulario_Notas = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();

        jMenu5.setText("jMenu5");

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanelEscritorioLayout = new javax.swing.GroupLayout(jPanelEscritorio);
        jPanelEscritorio.setLayout(jPanelEscritorioLayout);
        jPanelEscritorioLayout.setHorizontalGroup(
            jPanelEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 769, Short.MAX_VALUE)
        );
        jPanelEscritorioLayout.setVerticalGroup(
            jPanelEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 582, Short.MAX_VALUE)
        );

        jMenu1.setText("Archivos");

        jMenuItemArchivos_Salir.setText("Salir");
        jMenuItemArchivos_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemArchivos_SalirActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemArchivos_Salir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Materias");

        jMenuItemMaterias_FormularioMateria.setText("Formulario Materia");
        jMenuItemMaterias_FormularioMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMaterias_FormularioMateriaActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemMaterias_FormularioMateria);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Alumnos");

        jMenuItemAlumnos_FormularioAlumno.setText("Formulario Alumno");
        jMenuItemAlumnos_FormularioAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAlumnos_FormularioAlumnoActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemAlumnos_FormularioAlumno);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Inscripciones");

        jMenuItem_Inscripciones_FormularioInscripciones.setText("Formulario Inscripciones");
        jMenuItem_Inscripciones_FormularioInscripciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_Inscripciones_FormularioInscripcionesActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem_Inscripciones_FormularioInscripciones);

        jMenuBar1.add(jMenu4);

        jMenu6.setText("Carga de Notas");

        jMenuItem_CargaDeNotas_Formulario_Notas.setText("Formulario Carga de Notas");
        jMenuItem_CargaDeNotas_Formulario_Notas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_CargaDeNotas_Formulario_NotasActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem_CargaDeNotas_Formulario_Notas);

        jMenuBar1.add(jMenu6);

        jMenu7.setText("Consultas");
        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelEscritorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelEscritorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jMenuItemArchivos_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemArchivos_SalirActionPerformed
        this.setVisible(false);
        this.dispose();
        
    }//GEN-LAST:event_jMenuItemArchivos_SalirActionPerformed

    private void jMenuItemAlumnos_FormularioAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAlumnos_FormularioAlumnoActionPerformed
        // TODO add your handling code here:
        jPanelEscritorio.removeAll();
        jPanelEscritorio.repaint();
        VistaAlumno visA = new VistaAlumno();
        visA.setVisible(true);
        jPanelEscritorio.add(visA);
        
    }//GEN-LAST:event_jMenuItemAlumnos_FormularioAlumnoActionPerformed

    private void jMenuItemMaterias_FormularioMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMaterias_FormularioMateriaActionPerformed
        // TODO add your handling code here:
        jPanelEscritorio.removeAll();
        jPanelEscritorio.repaint();
        VistasMateria visM = new VistasMateria();
        visM.setVisible(true);
        jPanelEscritorio.add(visM);
    }//GEN-LAST:event_jMenuItemMaterias_FormularioMateriaActionPerformed

    private void jMenuItem_Inscripciones_FormularioInscripcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_Inscripciones_FormularioInscripcionesActionPerformed
        // TODO add your handling code here:
        jPanelEscritorio.removeAll();
        jPanelEscritorio.repaint();
        VistaInscripcion visI = new VistaInscripcion();
        visI.setVisible(true);
        jPanelEscritorio.add(visI);
    }//GEN-LAST:event_jMenuItem_Inscripciones_FormularioInscripcionesActionPerformed

    private void jMenuItem_CargaDeNotas_Formulario_NotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_CargaDeNotas_Formulario_NotasActionPerformed
        // TODO add your handling code here:
        jPanelEscritorio.removeAll();
        jPanelEscritorio.repaint();
        VistaCargaNota visCN = new VistaCargaNota();
        visCN.setVisible(true);
        jPanelEscritorio.add(visCN);
        Dimension tamEsc = jPanelEscritorio.getSize();
        Dimension tamFor = visCN.getSize();
        
        visCN.setLocation((tamEsc.width - tamFor.width)/2 , (tamEsc.height - tamFor.height)/2) ;
    }//GEN-LAST:event_jMenuItem_CargaDeNotas_Formulario_NotasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
        
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemAlumnos_FormularioAlumno;
    private javax.swing.JMenuItem jMenuItemArchivos_Salir;
    private javax.swing.JMenuItem jMenuItemMaterias_FormularioMateria;
    private javax.swing.JMenuItem jMenuItem_CargaDeNotas_Formulario_Notas;
    private javax.swing.JPanel jPanelEscritorio;
    // End of variables declaration//GEN-END:variables
}
