/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ulp.vista;

/**
 *
 * @author Genaro
 */
public class VistaAlumno extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaAlumnos
     */
    public VistaAlumno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jDayChooser1 = new com.toedter.calendar.JDayChooser();
        jl_alumnos = new javax.swing.JLabel();
        jl_idAlumno = new javax.swing.JLabel();
        jl_nombre = new javax.swing.JLabel();
        jl_fechaDeNac = new javax.swing.JLabel();
        jbt_guardar = new javax.swing.JButton();
        jbt_borrar = new javax.swing.JButton();
        jbt_actualizar = new javax.swing.JButton();
        jbt_limpiar = new javax.swing.JButton();
        jtf_idAlumno = new javax.swing.JTextField();
        jtf_nombre = new javax.swing.JTextField();
        jchb_activo = new javax.swing.JCheckBox();
        jbt_salir = new javax.swing.JButton();
        jl_activo = new javax.swing.JLabel();
        jdatec_fechaDeNac = new com.toedter.calendar.JDateChooser();

        jLabel5.setText("jLabel5");

        setTitle("Alumnos");

        jl_alumnos.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jl_alumnos.setText("Alumnos");

        jl_idAlumno.setText("Id Alumno");

        jl_nombre.setText("Nombre:");

        jl_fechaDeNac.setText("Fecha de Nacimieto:");

        jbt_guardar.setText("Guardar");
        jbt_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_guardarActionPerformed(evt);
            }
        });

        jbt_borrar.setText("Borrar");
        jbt_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_borrarActionPerformed(evt);
            }
        });

        jbt_actualizar.setText("Actualizar");
        jbt_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_actualizarActionPerformed(evt);
            }
        });

        jbt_limpiar.setText("Limpiar");

        jtf_idAlumno.setText("jTextField1");

        jtf_nombre.setText("jTextField2");

        jchb_activo.setText("jCheckBox1");

        jbt_salir.setText("Salir");
        jbt_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_salirActionPerformed(evt);
            }
        });

        jl_activo.setText("Activo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbt_guardar)
                        .addGap(18, 18, 18)
                        .addComponent(jbt_borrar)
                        .addGap(18, 18, 18)
                        .addComponent(jbt_actualizar)
                        .addGap(18, 18, 18)
                        .addComponent(jbt_limpiar)
                        .addGap(18, 18, 18)
                        .addComponent(jbt_salir)
                        .addGap(0, 31, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_idAlumno, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jl_nombre, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jl_fechaDeNac, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jl_activo, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jchb_activo)
                            .addComponent(jdatec_fechaDeNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_idAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(jl_alumnos)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jl_alumnos)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_idAlumno)
                    .addComponent(jtf_idAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_nombre)
                    .addComponent(jtf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jdatec_fechaDeNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_fechaDeNac))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jchb_activo)
                    .addComponent(jl_activo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbt_guardar)
                    .addComponent(jbt_borrar)
                    .addComponent(jbt_actualizar)
                    .addComponent(jbt_limpiar)
                    .addComponent(jbt_salir))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbt_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_guardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbt_guardarActionPerformed

    private void jbt_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_borrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbt_borrarActionPerformed

    private void jbt_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_salirActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
        
    }//GEN-LAST:event_jbt_salirActionPerformed

    private void jbt_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_actualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbt_actualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDayChooser jDayChooser1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jbt_actualizar;
    private javax.swing.JButton jbt_borrar;
    private javax.swing.JButton jbt_guardar;
    private javax.swing.JButton jbt_limpiar;
    private javax.swing.JButton jbt_salir;
    private javax.swing.JCheckBox jchb_activo;
    private com.toedter.calendar.JDateChooser jdatec_fechaDeNac;
    private javax.swing.JLabel jl_activo;
    private javax.swing.JLabel jl_alumnos;
    private javax.swing.JLabel jl_fechaDeNac;
    private javax.swing.JLabel jl_idAlumno;
    private javax.swing.JLabel jl_nombre;
    private javax.swing.JTextField jtf_idAlumno;
    private javax.swing.JTextField jtf_nombre;
    // End of variables declaration//GEN-END:variables
}
