/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ulp.vista;

import java.awt.Point;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;
import javax.swing.table.DefaultTableModel;
import ulp.entidades.Alumno;
import ulp.entidades.Materia;
import ulp.modelo.AlumnoData;
import ulp.modelo.Conexion;
import ulp.modelo.InscripcionesData;
import ulp.modelo.MateriaData;


/**
 *
 * @author Genaro
 */
public class VistaCargaNota extends javax.swing.JInternalFrame {
    private Conexion conexion = new Conexion();
    private MateriaData materia_Data = new MateriaData(conexion);
    private AlumnoData alumno_data = new AlumnoData(conexion);
    private InscripcionesData inscripcion_data = new InscripcionesData(conexion);
    
    private DefaultTableModel modelo;       //Para la tabla
    

    /**
     * Creates new form FormularioCargaNotas
     */
    public VistaCargaNota() {
        initComponents();
        
        this.jchb_porId.setSelected(true);
        this.jlIngreseApellido.setVisible(false);
        this.jl_ingreseDni.setVisible(false);
        this.jl_IngreseId.setVisible(true);
        this.jl_IngreseId.setLocation(new Point(20,3));
        this.jl_IngreseId.setLocation(new Point(20,3));
        this.jl_ingreseDni.setLocation(new Point(20,3));
        this.jtf_ingreseValor.setLocation(new Point(20,3));
       
        modelo=new DefaultTableModel();     //Instancio un nuevo modelo
        armaCabeceraTabla();
        borraFilasTabla();
        cargarMaterias();
    }
    
    public void armaCabeceraTabla(){
  
           //Titulos de Columnas
        ArrayList<Object> columnas=new ArrayList<Object>();
        columnas.add("ID Materia modelo");
        columnas.add("Nombre Materia");
        columnas.add("Nota");
       
        for(Object it:columnas){
        
            modelo.addColumn(it);
        }
        jTable_cargaNotas.setModel(modelo);
  }
    
     public void borraFilasTabla(){

        int a =jTable_cargaNotas.getRowCount()-1;

           for(int i=a;i>=0;i--){
   
                modelo.removeRow(i);
           }
}
    
    public void cargarMaterias(){
        List<Materia> materias = materia_Data.obtener_materias();
        for(Materia item: materias){
            jcb_materias.addItem(item);
        }
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jl_titulo = new javax.swing.JLabel();
        jButton_salir = new javax.swing.JButton();
        jButton_guardar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jchb_porId = new javax.swing.JCheckBox();
        jchb_porApellido = new javax.swing.JCheckBox();
        jchb_porDni = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_cargaNotas = new javax.swing.JTable();
        jButton_buscar = new javax.swing.JButton();
        jButton_limipar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jcb_materias = new javax.swing.JComboBox<>();
        jL_buscarMateria = new javax.swing.JLabel();
        jlIngreseApellido = new javax.swing.JLabel();
        jl_ingreseDni = new javax.swing.JLabel();
        jl_IngreseId = new javax.swing.JLabel();
        jtf_ingreseValor = new javax.swing.JTextField();
        jl_buscarAlumno = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel_nota = new javax.swing.JLabel();
        jTextField_nota = new javax.swing.JTextField();
        jtf_alumno = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setTitle("Carga de Notas");

        jl_titulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jl_titulo.setText("Carga de Notas de Alumno");

        jButton_salir.setText("Salir");
        jButton_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_salirActionPerformed(evt);
            }
        });

        jButton_guardar.setText("Guardar Nota");
        jButton_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_guardarActionPerformed(evt);
            }
        });

        buttonGroup1.add(jchb_porId);
        jchb_porId.setText("Por Id");
        jchb_porId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchb_porIdActionPerformed(evt);
            }
        });

        buttonGroup1.add(jchb_porApellido);
        jchb_porApellido.setText("Por Apellido");
        jchb_porApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchb_porApellidoActionPerformed(evt);
            }
        });

        buttonGroup1.add(jchb_porDni);
        jchb_porDni.setText("Por Dni");
        jchb_porDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchb_porDniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jchb_porId)
                    .addComponent(jchb_porDni)
                    .addComponent(jchb_porApellido))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jchb_porId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jchb_porApellido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jchb_porDni)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jTable_cargaNotas.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jTable_cargaNotas.setAutoscrolls(false);
        jTable_cargaNotas.setRowHeight(30);
        jScrollPane2.setViewportView(jTable_cargaNotas);

        jButton_buscar.setText("Buscar");
        jButton_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_buscarActionPerformed(evt);
            }
        });

        jButton_limipar.setText("Limpiar");
        jButton_limipar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_limiparActionPerformed(evt);
            }
        });

        jcb_materias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_materiasActionPerformed(evt);
            }
        });

        jL_buscarMateria.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jL_buscarMateria.setText("Buscar Materia");

        jlIngreseApellido.setLabelFor(jtf_ingreseValor);
        jlIngreseApellido.setText("Ingrese el Apellido:");

        jl_ingreseDni.setLabelFor(jtf_ingreseValor);
        jl_ingreseDni.setText("Ingrese el Dni:");

        jl_IngreseId.setLabelFor(jtf_ingreseValor);
        jl_IngreseId.setText("Ingrese el Id:");

        jtf_ingreseValor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jl_buscarAlumno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jl_buscarAlumno.setText("Buscar Alumno");

        jLabel1.setText("Id Inscripcion:");

        jLabel2.setText("Numero");

        jLabel_nota.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_nota.setText("Nota:");

        jTextField_nota.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField_nota.setText("10,00");
        jTextField_nota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_notaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel_nota))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextField_nota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_nota)
                .addGap(18, 18, 18)
                .addComponent(jTextField_nota)
                .addGap(8, 8, 8))
        );

        jtf_alumno.setEditable(false);
        jtf_alumno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtf_alumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_alumnoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jtf_alumno, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jL_buscarMateria)
                        .addGap(18, 18, 18)
                        .addComponent(jcb_materias, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jl_buscarAlumno)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jl_IngreseId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jl_ingreseDni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlIngreseApellido))
                    .addComponent(jtf_ingreseValor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jl_buscarAlumno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_IngreseId)
                            .addComponent(jl_ingreseDni)
                            .addComponent(jlIngreseApellido))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_ingreseValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jL_buscarMateria)
                            .addComponent(jcb_materias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jtf_alumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(jButton_buscar)
                .addGap(18, 18, 18)
                .addComponent(jButton_limipar)
                .addGap(18, 18, 18)
                .addComponent(jButton_guardar)
                .addGap(18, 18, 18)
                .addComponent(jButton_salir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jl_titulo)
                        .addGap(33, 33, 33)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jl_titulo)
                        .addGap(27, 27, 27)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_buscar)
                    .addComponent(jButton_limipar)
                    .addComponent(jButton_guardar)
                    .addComponent(jButton_salir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jchb_porDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchb_porDniActionPerformed
        // TODO add your handling code here:
        this.jl_IngreseId.setVisible(false);
        this.jlIngreseApellido.setVisible(false);
        this.jl_ingreseDni.setVisible(true);
    }//GEN-LAST:event_jchb_porDniActionPerformed

    private void jchb_porApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchb_porApellidoActionPerformed
        // TODO add your handling code here:
        this.jl_IngreseId.setVisible(false);
        this.jl_ingreseDni.setVisible(false);
        this.jlIngreseApellido.setVisible(true);
    }//GEN-LAST:event_jchb_porApellidoActionPerformed

    private void jButton_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_salirActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButton_salirActionPerformed

    private void jchb_porIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchb_porIdActionPerformed
        // TODO add your handling code here:
        this.jlIngreseApellido.setVisible(false);
        this.jl_ingreseDni.setVisible(false);
        this.jl_IngreseId.setVisible(true);
    }//GEN-LAST:event_jchb_porIdActionPerformed

    private void jcb_materiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_materiasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_materiasActionPerformed

    private void jTextField_notaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_notaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_notaActionPerformed

    private void jButton_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_buscarActionPerformed
        // TODO add your handling code here:
        borraFilasTabla();      //Borra los datos de la tabla
        Alumno elAlumno = new Alumno();
        elAlumno = alumno_data.buscar_alumno(Integer.parseInt(jtf_ingreseValor.getText()));
        
        System.out.println(elAlumno);
        
        jtf_alumno.setText(elAlumno.getApellido()+" "+elAlumno.getNombre());
        
        Map<Materia, Double> notas = new TreeMap<>();
        notas = inscripcion_data.notas_alumno(elAlumno.getId_alumno());

            int i= 0;
        for (Map.Entry<Materia, Double> entry : notas.entrySet()) {
        
            Materia key = entry.getKey();
            Double value = entry.getValue();
            
            modelo.addRow(new Object[]{key.getId_materia(),key.getNombre_materia(),entry.getValue()});
            
       i++;
        }
        

        
    }//GEN-LAST:event_jButton_buscarActionPerformed

    private void jtf_alumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_alumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_alumnoActionPerformed

    private void jButton_limiparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_limiparActionPerformed
        // TODO add your handling code here:
        this.borraFilasTabla();
    }//GEN-LAST:event_jButton_limiparActionPerformed

    private void jButton_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_guardarActionPerformed
        // TODO add your handling code here:
        Alumno elAlumno = new Alumno();
        Materia laMateria = new Materia();
//        elAlumno = alumno_data.buscar_alumno();
        
        if(jtf_alumno!=null){
            
        }
    }//GEN-LAST:event_jButton_guardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton_buscar;
    private javax.swing.JButton jButton_guardar;
    private javax.swing.JButton jButton_limipar;
    private javax.swing.JButton jButton_salir;
    private javax.swing.JLabel jL_buscarMateria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_nota;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    public javax.swing.JTable jTable_cargaNotas;
    private javax.swing.JTextField jTextField_nota;
    private javax.swing.JComboBox<Materia> jcb_materias;
    private javax.swing.JCheckBox jchb_porApellido;
    private javax.swing.JCheckBox jchb_porDni;
    private javax.swing.JCheckBox jchb_porId;
    private javax.swing.JLabel jlIngreseApellido;
    private javax.swing.JLabel jl_IngreseId;
    private javax.swing.JLabel jl_buscarAlumno;
    private javax.swing.JLabel jl_ingreseDni;
    private javax.swing.JLabel jl_titulo;
    private javax.swing.JTextField jtf_alumno;
    private javax.swing.JTextField jtf_ingreseValor;
    // End of variables declaration//GEN-END:variables
}
