/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ulp.vista;

import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import ulp.entidades.Alumno;
import ulp.entidades.Inscripcion;
import ulp.entidades.Materia;
import ulp.modelo.AlumnoData;
import ulp.modelo.Conexion;
import ulp.modelo.InscripcionesData;
import ulp.modelo.MateriaData;

/**
 *
 * @author Genaro
 */
public class VistaCargaNota extends javax.swing.JInternalFrame {

    private Conexion conexion;
    private MateriaData materia_Data;
    private AlumnoData alumno_data;
    private InscripcionesData inscripcion_data;
    private DefaultTableModel modelo;       //Para la tabla
    private Alumno alumnoAux;
    private Materia materiaAux;

    public Materia getMateria() {
        return materiaAux;
    }

    public void setMateria(Materia materia) {
        this.materiaAux = materia;
    }

    public Alumno getAlumno() {
        return alumnoAux;
    }

    public void setAlumno(Alumno alumno) {
        this.alumnoAux = alumno;
    }

    /**
     * Creates new form FormularioCargaNotas
     */
    public VistaCargaNota() {
        initComponents();
        conexion = new Conexion();
        materia_Data = new MateriaData(conexion);
        alumno_data = new AlumnoData(conexion);
        inscripcion_data = new InscripcionesData(conexion);
        modelo = new DefaultTableModel();     //Instancio un nuevo modelo
        

        this.jchb_porId.setSelected(true);
        this.jl_ingreseDni.setVisible(false);
        this.jl_IngreseId.setLocation(new Point(20, 3));
        this.jl_IngreseId.setLocation(new Point(20, 3));
        this.jl_ingreseDni.setLocation(new Point(20, 3));
        this.jtf_ingreseValor.setLocation(new Point(20, 3));
        jcb_alumno.setEnabled(false);
        jcb_materias.setEnabled(false);
        jFormattedTextField_nota.setEditable(true);
        jl_nombreAlumno.setVisible(true);
        limpiar();
        



    }
    
    

    public void limpiarInscripcion() {
        jl_nombreMateria.setText("");
        jl_iDmateria.setText("");
        jl_numeroInscr.setText("");
        jFormattedTextField_nota.setText("");
        jFormattedTextField_nota.setEnabled(false);

    }


    public void cargarMateriasxAlumno(Alumno alumno) {
        
        jcb_materias.removeAllItems();
              
        List<Materia> materias = inscripcion_data.materias_alumno(alumno.getId_alumno());
        for (Materia item: materias) {
            jcb_materias.addItem(item);
        }
        
        
    }
    public void cargarAlumnos() {

        jcb_alumno.removeAllItems();
//        jcb_alumno.setSelectedItem(new Object[]{" "});
        List<Alumno> alumnos = alumno_data.ver_alumnos_activos();
        alumnos.forEach((item) -> {
            jcb_alumno.addItem(item);
        });
//        jcb_alumno.setSelectedItem(null);
    }
    
    public void mostrarInscripciones(){
        Materia materia;
        materia = getMateria();
        Alumno alumno;
        alumno = getAlumno();
        System.out.println(alumno);
        System.out.println(materia);
        
        Inscripcion inscripcion;
        
        inscripcion = (Inscripcion)inscripcion_data.buscar_inscripcion(alumno, materia);
        
        if(inscripcion != null){
        
        System.out.println(inscripcion);
        
        jl_numeroInscr.setText(String.valueOf(inscripcion.getId_inscripcion()));
        jl_iDmateria.setText(String.valueOf(String.valueOf(materia.getId_materia())));
        jl_nombreMateria.setText(materia.getNombre_materia());
        jFormattedTextField_nota.setText(String.valueOf(inscripcion.getCalificacion()));
        }
        
    }

             
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jl_titulo = new javax.swing.JLabel();
        jButton_salir = new javax.swing.JButton();
        jButton_guardar = new javax.swing.JButton();
        javax.swing.JButton jButton_limpiar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jl_buscarAlumno = new javax.swing.JLabel();
        jlIngreseApellido = new javax.swing.JLabel();
        jl_IngreseId = new javax.swing.JLabel();
        jl_ingreseDni = new javax.swing.JLabel();
        jl_PorCombobox = new javax.swing.JLabel();
        jtf_ingreseValor = new javax.swing.JTextField();
        jcb_alumno = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jchb_porId = new javax.swing.JCheckBox();
        jchb_porDni = new javax.swing.JCheckBox();
        jchb_porCombo = new javax.swing.JCheckBox();
        jButton_buscar = new javax.swing.JButton();
        jL_buscarMateria = new javax.swing.JLabel();
        jcb_materias = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel_nota = new javax.swing.JLabel();
        jFormattedTextField_nota = new javax.swing.JFormattedTextField();
        jl_nombreAlumno = new javax.swing.JLabel();
        jl_idAlumno = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jb_buscInscri = new javax.swing.JButton();
        jl_numeroInscr = new javax.swing.JTextField();
        jl_nombreMateria = new javax.swing.JTextField();
        jl_iDmateria = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        setResizable(false);
        setTitle("Carga de Notas");
        setPreferredSize(new java.awt.Dimension(565, 625));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_titulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jl_titulo.setText("Carga de Notas de Alumno");
        getContentPane().add(jl_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jButton_salir.setText("Salir");
        jButton_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_salirActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 520, -1, -1));

        jButton_guardar.setText("Guardar Nota");
        jButton_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_guardarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 520, -1, -1));

        jButton_limpiar.setText("Limpiar");
        jButton_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_limpiarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 520, -1, -1));

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jl_buscarAlumno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jl_buscarAlumno.setText("Buscar Alumno");

        jlIngreseApellido.setLabelFor(jtf_ingreseValor);
        jlIngreseApellido.setText("Ingrese ");

        jl_IngreseId.setLabelFor(jtf_ingreseValor);
        jl_IngreseId.setText("ID:");

        jl_ingreseDni.setLabelFor(jtf_ingreseValor);
        jl_ingreseDni.setText(" DNI:");

        jl_PorCombobox.setLabelFor(jtf_ingreseValor);
        jl_PorCombobox.setText("Por ComboBox");

        jtf_ingreseValor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtf_ingreseValor.setNextFocusableComponent(jcb_materias);
        jtf_ingreseValor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtf_ingreseValorFocusLost(evt);
            }
        });
        jtf_ingreseValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_ingreseValorActionPerformed(evt);
            }
        });
        jtf_ingreseValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_ingreseValorKeyTyped(evt);
            }
        });

        jcb_alumno.setNextFocusableComponent(jButton_buscar);
        jcb_alumno.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcb_alumnoItemStateChanged(evt);
            }
        });
        jcb_alumno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jcb_alumnoFocusLost(evt);
            }
        });
        jcb_alumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcb_alumnoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jcb_alumnoMouseEntered(evt);
            }
        });
        jcb_alumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_alumnoActionPerformed(evt);
            }
        });

        buttonGroup1.add(jchb_porId);
        jchb_porId.setText("Por Id");
        jchb_porId.setFocusable(false);
        jchb_porId.setNextFocusableComponent(jtf_ingreseValor);
        jchb_porId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchb_porIdActionPerformed(evt);
            }
        });

        buttonGroup1.add(jchb_porDni);
        jchb_porDni.setText("Por Dni");
        jchb_porDni.setFocusable(false);
        jchb_porDni.setNextFocusableComponent(jtf_ingreseValor);
        jchb_porDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchb_porDniActionPerformed(evt);
            }
        });

        buttonGroup1.add(jchb_porCombo);
        jchb_porCombo.setText("Por Combo");
        jchb_porCombo.setFocusable(false);
        jchb_porCombo.setNextFocusableComponent(jchb_porCombo);
        jchb_porCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchb_porComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jchb_porId)
                    .addComponent(jchb_porDni)
                    .addComponent(jchb_porCombo))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jchb_porId, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jchb_porDni)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jchb_porCombo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton_buscar.setText("Buscar");
        jButton_buscar.setNextFocusableComponent(jFormattedTextField_nota);
        jButton_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_buscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_ingreseValor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jlIngreseApellido)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jl_IngreseId)
                                .addGap(0, 0, 0)
                                .addComponent(jl_ingreseDni))
                            .addComponent(jl_buscarAlumno)
                            .addComponent(jl_PorCombobox))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jcb_alumno, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addComponent(jButton_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jl_buscarAlumno)
                        .addGap(28, 28, 28)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_IngreseId)
                            .addComponent(jl_ingreseDni)
                            .addComponent(jlIngreseApellido))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_ingreseValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addComponent(jl_PorCombobox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcb_alumno, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 475, 210));

        jL_buscarMateria.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jL_buscarMateria.setText("Elegir Materia");
        getContentPane().add(jL_buscarMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        jcb_materias.setEditable(true);
        jcb_materias.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcb_materias.setNextFocusableComponent(jButton_buscar);
        jcb_materias.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcb_materiasItemStateChanged(evt);
            }
        });
        jcb_materias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_materiasActionPerformed(evt);
            }
        });
        getContentPane().add(jcb_materias, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 190, -1));

        jLabel_nota.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_nota.setText("Nota:");

        jFormattedTextField_nota.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        jFormattedTextField_nota.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jFormattedTextField_nota.setNextFocusableComponent(jButton_guardar);
        jFormattedTextField_nota.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedTextField_notaFocusLost(evt);
            }
        });
        jFormattedTextField_nota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField_notaActionPerformed(evt);
            }
        });
        jFormattedTextField_nota.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFormattedTextField_notaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFormattedTextField_nota)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel_nota, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 10, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_nota)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextField_nota, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, -1, -1));

        jl_nombreAlumno.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jl_nombreAlumno.setText("Nombre");
        jl_nombreAlumno.setToolTipText("");
        jl_nombreAlumno.setFocusable(false);
        jl_nombreAlumno.setRequestFocusEnabled(false);
        getContentPane().add(jl_nombreAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, -1, -1));

        jl_idAlumno.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jl_idAlumno.setText("ID");
        getContentPane().add(jl_idAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("ID INSCRIPCION:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 160, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("ID MATERIA:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 130, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("NOMBRE MATERIA:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, -1, -1));

        jb_buscInscri.setText("Buscar Inscripcion");
        jb_buscInscri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_buscInscriActionPerformed(evt);
            }
        });
        getContentPane().add(jb_buscInscri, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, 150, 30));

        jl_numeroInscr.setEditable(false);
        jl_numeroInscr.setBackground(new java.awt.Color(204, 204, 204));
        jl_numeroInscr.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jl_numeroInscr.setFocusable(false);
        getContentPane().add(jl_numeroInscr, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 80, 30));

        jl_nombreMateria.setEditable(false);
        jl_nombreMateria.setBackground(new java.awt.Color(204, 204, 204));
        jl_nombreMateria.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jl_nombreMateria.setFocusable(false);
        getContentPane().add(jl_nombreMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 470, 230, 30));

        jl_iDmateria.setEditable(false);
        jl_iDmateria.setBackground(new java.awt.Color(204, 204, 204));
        jl_iDmateria.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jl_iDmateria.setFocusable(false);
        getContentPane().add(jl_iDmateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, 80, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jchb_porDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchb_porDniActionPerformed
        // TODO add your handling code here:
        limpiar();
        this.jl_IngreseId.setVisible(false);
        this.jl_ingreseDni.setVisible(true);
        jtf_ingreseValor.setEnabled(true);
        jcb_alumno.setEnabled(false);
        this.escribirEstados("Ha elegido buscar por Dni, ingrese un numero valido");
        
        

    }//GEN-LAST:event_jchb_porDniActionPerformed

    private void jButton_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_salirActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButton_salirActionPerformed

    private void jchb_porIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchb_porIdActionPerformed
        // TODO add your handling code here:
        limpiar();
        this.jl_ingreseDni.setVisible(false);
        this.jl_IngreseId.setVisible(true);
        jtf_ingreseValor.setEnabled(true);
        jcb_alumno.setEnabled(false);
        this.escribirEstados("Ha elegido buscar por Id, ingrese un numero valido");
        

    }//GEN-LAST:event_jchb_porIdActionPerformed

    private void jcb_materiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_materiasActionPerformed
        // TODO add your handling code here:
        System.out.println("eligo materia");
        limpiarInscripcion();
        
        Alumno alumno = getAlumno();
        System.out.println(alumno);
        
         Materia materia = (Materia) jcb_materias.getSelectedItem();
         
         System.out.println(materia);
        if (materia != null && alumno != null) {
            setMateria(materia);
            jb_buscInscri.setEnabled(true);
//            
            System.out.println("mando a imprimir la inscripcion");
        } else {
            System.out.println("algo paso aca");
        }
        
        
//               
        
    }//GEN-LAST:event_jcb_materiasActionPerformed

    private void jButton_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_buscarActionPerformed
        // TODO add your handling code here:

        

            Alumno elAlumno = null;

            if (jchb_porId.isSelected()) {
                try {
                    elAlumno = alumno_data.buscar_alumno(Integer.parseInt(jtf_ingreseValor.getText()));
                } catch (NumberFormatException e) {
                    System.out.println("No se puede convertir a numero");
                }

            }
            if (jchb_porDni.isSelected()) {
                elAlumno = alumno_data.buscar_alumno(jtf_ingreseValor.getText());

            }
            if (jchb_porCombo.isSelected()) {
                elAlumno = (Alumno) jcb_alumno.getSelectedItem();

            }
            if (elAlumno != null) {
                jl_nombreAlumno.setText(elAlumno.getApellido() + " " + elAlumno.getNombre());
                jl_idAlumno.setText(String.valueOf(elAlumno.getId_alumno()));
                jl_nombreAlumno.setVisible(true);
                jcb_materias.setEnabled(true);
                
                setAlumno(elAlumno);
                cargarMateriasxAlumno(elAlumno);
                jcb_alumno.setEnabled(false);
                jButton_buscar.setEnabled(false);
                
                
           
        }
    }//GEN-LAST:event_jButton_buscarActionPerformed

    private void jButton_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_limpiarActionPerformed
        // TODO add your handling code here:
        Alumno alumno=null;
        limpiar();
    }//GEN-LAST:event_jButton_limpiarActionPerformed

    private void jButton_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_guardarActionPerformed
        // TODO add your handling code here:
        
        // 
        String mensaje=
                "\"¿Seguro que desea actualizar?\n"
                + "La nueva nota pasara a ser \n"
                + Double.parseDouble(jFormattedTextField_nota.getText())+" ";
        if(Double.parseDouble(jFormattedTextField_nota.getText()) > 10){
        JOptionPane.showMessageDialog(this, "Valor incoorrecto, debe ser entre 0 y 10");
        jFormattedTextField_nota.requestFocus();
    } else {
        
       
        int respuesta = JOptionPane.showConfirmDialog(this, mensaje, "Actualizar Nota" , JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            //JOptionPane.showMessageDialog(this, respuesta);
            if (respuesta == 0) {
               
        if(!jl_numeroInscr.getText().equals("")){
            try{
                
            inscripcion_data.registrar_nota(Integer.parseInt(jl_numeroInscr.getText()), Double.parseDouble(jFormattedTextField_nota.getText()));
          } catch (NumberFormatException e){
              System.out.println("No se puede convertir a numero");
          }
            
            limpiar();
        }
            
            System.out.println("ingreso la nota");
            try{
            System.out.println(Double.parseDouble(jFormattedTextField_nota.getText()));
            }catch (NumberFormatException e){
              System.out.println("No se puede convertir a numero");
            }
            
           
        }
        }
        
    }//GEN-LAST:event_jButton_guardarActionPerformed

    private void jtf_ingreseValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_ingreseValorActionPerformed
        // TODO add your handling code here:
//        
    }//GEN-LAST:event_jtf_ingreseValorActionPerformed

    private void jcb_materiasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcb_materiasItemStateChanged
        // TODO add your handling code here:
        
  
    }//GEN-LAST:event_jcb_materiasItemStateChanged

    private void jtf_ingreseValorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtf_ingreseValorFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_ingreseValorFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jchb_porComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchb_porComboActionPerformed
        // TODO add your handling code here:
        limpiar();
        this.jl_ingreseDni.setVisible(false);
        this.jl_IngreseId.setVisible(false);
        this.jtf_ingreseValor.setEnabled(false);
        jcb_alumno.setEnabled(true);
        escribirEstados("Ha elegido buscar por ComboBox, Eliga un alumna de la lista desplegable");
        jl_PorCombobox.setVisible(true);
        jtf_ingreseValor.setText(" ");
        jtf_ingreseValor.setEnabled(true);
        jFormattedTextField_nota.setText(" ");
        jFormattedTextField_nota.setEnabled(true);
        cargarAlumnos();
        jcb_alumno.requestFocus();
    }//GEN-LAST:event_jchb_porComboActionPerformed

    private void jcb_alumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_alumnoActionPerformed
        // TODO add your handling code here:
        limpiarInscripcion();
//        setAlumno(null);
//        jcb_materias.setSelectedItem(null);
    }//GEN-LAST:event_jcb_alumnoActionPerformed

    private void jcb_alumnoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcb_alumnoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_alumnoMouseEntered

    private void jcb_alumnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcb_alumnoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_alumnoMouseClicked

    private void jcb_alumnoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jcb_alumnoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_alumnoFocusLost

    private void jcb_alumnoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcb_alumnoItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_alumnoItemStateChanged

    private void jFormattedTextField_notaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField_notaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField_notaActionPerformed

    private void jFormattedTextField_notaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextField_notaFocusLost
        // TODO add your handling code here:
        jButton_guardar.setEnabled(true);
    }//GEN-LAST:event_jFormattedTextField_notaFocusLost

    private void jb_buscInscriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_buscInscriActionPerformed
        // TODO add your handling code here:
        
        System.out.println("presionado el boton");
        
            mostrarInscripciones();
            jFormattedTextField_nota.setEnabled(true);
        
        System.out.println("mande imprimr");
        
        
    }//GEN-LAST:event_jb_buscInscriActionPerformed

    private void jFormattedTextField_notaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextField_notaKeyTyped
        // TODO add your handling code here:
        jButton_guardar.setEnabled(true);
       
       
       try{
        char caracter = evt.getKeyChar();
        // Verificar si la tecla pulsada no es un digito
        if (((caracter < '0')
                || (caracter > '9'))
              && (caracter != '\b' /*corresponde a BACK_SPACE*/) &&(caracter != '.') &&(caracter != ',')) {
            evt.consume();  // ignorar el evento de teclado
        }
       } catch (NumberFormatException e){
              System.out.println("No se puede convertir a numero");
       }
       
       
        

       
        
    }//GEN-LAST:event_jFormattedTextField_notaKeyTyped

    private void jtf_ingreseValorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_ingreseValorKeyTyped
        // TODO add your handling code here:
        
        char caracter = evt.getKeyChar();
        if (!(((caracter < '0') || (caracter > '9')) && (caracter != '\b'))) {
            
        } else {
            
            evt.consume();
        }

    }//GEN-LAST:event_jtf_ingreseValorKeyTyped

    public void limpiar() {
        
        jb_buscInscri.setEnabled(false);
        jtf_ingreseValor.setText("");
        jl_nombreMateria.setText("");
        jl_iDmateria.setText("");
        jl_numeroInscr.setText("");
        jFormattedTextField_nota.setText("");
        jcb_materias.setSelectedItem(null);
        jcb_alumno.setSelectedItem(null);
        jcb_materias.setEnabled(false);
        jl_idAlumno.setText("");
        jl_nombreAlumno.setText("");
        jButton_guardar.setEnabled(false);
        setAlumno(null);
        setMateria(null);
        if(jchb_porCombo.isSelected()){
            jcb_alumno.setEnabled(true);
        }
        
        jButton_buscar.setEnabled(true);

               
        hacerFoco();
    }

    public void escribirEstados(String estado) {
//        jl_estadosYMensajes.setText(estado);
//        int delay = 5000; // miliseg
//        ActionListener taskPerformer = (ActionEvent evt) -> {
//            jl_estadosYMensajes.setVisible(false);
//        };
//
//
//        Timer timer = new Timer (delay,taskPerformer );
//        timer.setRepeats(false);
//        timer.start();
//        

    }

    public void hacerFoco() {
        jtf_ingreseValor.requestFocus();
    }

//  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_buscar;
    private javax.swing.JButton jButton_guardar;
    private javax.swing.JButton jButton_salir;
    private javax.swing.JFormattedTextField jFormattedTextField_nota;
    private javax.swing.JLabel jL_buscarMateria;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_nota;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jb_buscInscri;
    private javax.swing.JComboBox<Alumno> jcb_alumno;
    private javax.swing.JComboBox<Materia> jcb_materias;
    private javax.swing.JCheckBox jchb_porCombo;
    private javax.swing.JCheckBox jchb_porDni;
    private javax.swing.JCheckBox jchb_porId;
    private javax.swing.JLabel jlIngreseApellido;
    private javax.swing.JLabel jl_IngreseId;
    private javax.swing.JLabel jl_PorCombobox;
    private javax.swing.JLabel jl_buscarAlumno;
    private javax.swing.JTextField jl_iDmateria;
    private javax.swing.JLabel jl_idAlumno;
    private javax.swing.JLabel jl_ingreseDni;
    private javax.swing.JLabel jl_nombreAlumno;
    private javax.swing.JTextField jl_nombreMateria;
    private javax.swing.JTextField jl_numeroInscr;
    private javax.swing.JLabel jl_titulo;
    private javax.swing.JTextField jtf_ingreseValor;
    // End of variables declaration//GEN-END:variables
}
