/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ulp.vista;

import java.util.List;
import ulp.entidades.Alumno;
import ulp.modelo.AlumnoData;
import ulp.modelo.Conexion;

/**
 *
 * @author Genaro
 */
public class VistaInscripcion extends javax.swing.JInternalFrame {
    
    private Conexion conexion = new Conexion();
    private AlumnoData alumno_Data = new AlumnoData(conexion);

    /**
     * Creates new form VistaInscripciones
     */
    public VistaInscripcion() {
        initComponents();
        this.cargarAlumnos();
        this.jrb_inscripto.setSelected(true);
    }
    
    public void cargarAlumnos(){
        List<Alumno> alumnos = alumno_Data.ver_alumnos();
        for(Alumno item: alumnos){
            jcb_alumno.addItem(item);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jl_inscribir = new javax.swing.JButton();
        jl_anularInscripcion = new javax.swing.JButton();
        jl_salir = new javax.swing.JButton();
        jl_alumno = new javax.swing.JLabel();
        jcb_alumno = new javax.swing.JComboBox<>();
        jL_tituloFormulario = new javax.swing.JLabel();
        jrb_inscripto = new javax.swing.JRadioButton();
        jrb_disponiblesParaInscribir = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_tablaInscripciones = new javax.swing.JTable();

        jl_inscribir.setText("INSCRIBIR");

        jl_anularInscripcion.setText("ANULAR INSCRIPCON");

        jl_salir.setText("SALIR");
        jl_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jl_salirActionPerformed(evt);
            }
        });

        jl_alumno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jl_alumno.setText("ALUMNO:");

        jcb_alumno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jcb_alumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_alumnoActionPerformed(evt);
            }
        });

        jL_tituloFormulario.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jL_tituloFormulario.setText("FORMULARIO DE INSCRIPCIONES");

        buttonGroup1.add(jrb_inscripto);
        jrb_inscripto.setText("INSCRIPTO");
        jrb_inscripto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_inscriptoActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrb_disponiblesParaInscribir);
        jrb_disponiblesParaInscribir.setText("DISPONIBLES PARA INSCRIBIR");
        jrb_disponiblesParaInscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_disponiblesParaInscribirActionPerformed(evt);
            }
        });

        jt_tablaInscripciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jt_tablaInscripciones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(jl_inscribir)
                        .addGap(40, 40, 40)
                        .addComponent(jl_anularInscripcion)
                        .addGap(39, 39, 39)
                        .addComponent(jl_salir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(jrb_inscripto)
                        .addGap(65, 65, 65)
                        .addComponent(jrb_disponiblesParaInscribir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jL_tituloFormulario))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jl_alumno)
                        .addGap(18, 18, 18)
                        .addComponent(jcb_alumno, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcb_alumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_alumno))
                .addGap(59, 59, 59)
                .addComponent(jL_tituloFormulario)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrb_inscripto)
                    .addComponent(jrb_disponiblesParaInscribir))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jl_anularInscripcion)
                    .addComponent(jl_salir)
                    .addComponent(jl_inscribir))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrb_inscriptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_inscriptoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrb_inscriptoActionPerformed

    private void jrb_disponiblesParaInscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_disponiblesParaInscribirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrb_disponiblesParaInscribirActionPerformed

    private void jcb_alumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_alumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_alumnoActionPerformed

    private void jl_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jl_salirActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jl_salirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jL_tituloFormulario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<Alumno> jcb_alumno;
    private javax.swing.JLabel jl_alumno;
    private javax.swing.JButton jl_anularInscripcion;
    private javax.swing.JButton jl_inscribir;
    private javax.swing.JButton jl_salir;
    private javax.swing.JRadioButton jrb_disponiblesParaInscribir;
    private javax.swing.JRadioButton jrb_inscripto;
    private javax.swing.JTable jt_tablaInscripciones;
    // End of variables declaration//GEN-END:variables
}
